"""Matched-threshold / operating-curve view of the encoder-seed ablation
(reviewer R2): the headline 2x2 (tab_ablation) compares all four conditions at
a single common threshold t=0.20, which R2 flags as confounded --- conditions
have different calibration and guard counts, so a probe that floods vertices
shows a short tail simply by over-guarding.

This table removes that confound by reporting every condition across the whole
swept operating curve t in {0.20, 0.25, 0.30}, so conditions can be compared at
a matched guard budget |S|/n rather than a matched threshold. Aggregation is the
four-seed mean, on the 362-polygon leak-free dev_test split (same data as
tab_ablation), reusing the stored per-polygon JSONs --- no GPU.

Output: paper/tables/tab_ablation_thresholds.tex
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
PDATA = REPO / "paper" / "data"
TABLE = REPO / "paper" / "tables" / "tab_ablation_thresholds.tex"

CONDS = [
    ("\\SetPredictor{} full",           "full",
     ["dist_dev_test.json", "dist_dev_test_seed11.json",
      "dist_dev_test_seed22.json", "dist_dev_test_seed33.json"]),
    ("\\quad no-seed (encoder only)",   "noseed",
     [f"dist_dev_test_noseed_seed{s}.json" for s in (1234, 11, 22, 33)]),
    ("\\quad no-encoder (seed only)",   "noenc",
     ["dist_dev_test_noenc.json"]
     + [f"dist_dev_test_noenc_seed{s}.json" for s in (11, 22, 33)]),
    ("\\quad coords-only (neither)",    "noseednoenc",
     [f"dist_dev_test_noseednoenc_seed{s}.json" for s in (1234, 11, 22, 33)]),
]
THRESHOLDS = [("0.20", "probe_t020"), ("0.25", "probe_t025"), ("0.30", "probe_t030")]


def cond_threshold_stats(files, key):
    """Four-seed mean of (|S|/n, |S|/OPT, #Cov<0.99, min Cov) at one threshold."""
    sn, so, below, mincov = [], [], [], []
    for f in files:
        fp = PDATA / f
        d = json.load(open(fp))["polygons"]
        sn.append(np.mean([r[key]["S_size"] / r["n"] for r in d]))
        so.append(np.mean([r[key]["S_size"] / r["OPT"] for r in d if r.get("OPT")]))
        below.append(sum(1 for r in d if r[key]["cov"] < 0.99))
        mincov.append(min(r[key]["cov"] for r in d))
    return (float(np.mean(sn)), float(np.mean(so)),
            float(np.mean(below)), float(np.mean(mincov)))


def main() -> None:
    rows = []
    rows.append("% auto-generated by build_matched_threshold_table.py")
    rows.append("\\begin{tabular}{llrrrr}")
    rows.append("  \\toprule")
    rows.append("  Probe inputs & $t$ & $|S|/n$ & $|S|/\\OPT$ & "
                "$\\#\\{\\mathrm{Cov}<0.99\\}$ & $\\min\\mathrm{Cov}$ \\\\")
    rows.append("  \\midrule")
    for i, (label, _slug, files) in enumerate(CONDS):
        for j, (tlab, key) in enumerate(THRESHOLDS):
            s_n, s_o, blw, mc = cond_threshold_stats(files, key)
            name = label if j == 0 else ""
            rows.append(f"  {name} & {tlab} & {s_n:.2f} & {s_o:.2f} & "
                        f"{blw:.1f} & {mc:.3f} \\\\")
        if i < len(CONDS) - 1:
            rows.append("  \\midrule")
    rows.append("  \\bottomrule")
    rows.append("\\end{tabular}")
    TABLE.write_text("\n".join(rows) + "\n")
    print(f"wrote {TABLE}")
    print("\n".join(rows))


if __name__ == "__main__":
    main()
