#!/usr/bin/env python
"""build_operating_curve_table.py — the probe's full coverage/cost operating curve.

The main tables report only t in {0.20, 0.25, 0.30}, which are the three most
guard-expensive points on the curve. paper/data/setpred_iter_sweep.json already
contains six more (t = 0.50 ... 0.80) at K=1, reaching |S|/OPT as low as ~1.06.
They were computed for the fixed-point experiment (fig:mechanism) and never
reported as an operating curve.

This script emits tables/tab_operating_curve.tex covering the whole range, plus
the policy-seed baseline from the same file as a reference row.

CAVEAT baked into the caption: this sweep is the combined dev+test pool
(1224 polygons), displayed seed 1234, whereas tab_headline is test-only (362)
and a four-seed mean. The two are NOT cell-for-cell comparable; the curve is
reported for its shape, not to restate the headline numbers.

Usage:  python paper/scripts/build_operating_curve_table.py
"""
from __future__ import annotations

import json
import pathlib

REPO = pathlib.Path(__file__).resolve().parents[2]
SWEEP = REPO / "paper/data/setpred_iter_sweep.json"
DIST = REPO / "paper/data/setpred_dev_test.json"
OUT = REPO / "paper/tables/tab_operating_curve.tex"

def _fmt(v, nd=3):
    return f"${v:.{nd}f}$" if isinstance(v, (int, float)) else "---"


def _single_pass_cells(cells: dict):
    """Yield (threshold, cell) for single-pass entries.

    Key formats differ between files: setpred_dev_test.json uses 't=0.2|K=1'
    while setpred_iter_sweep.json uses 't=0.5|K=1', and trailing-zero styles are
    inconsistent ('0.2' vs '0.20'), so parse the float rather than string-match.
    """
    for key, v in cells.items():
        if not isinstance(v, dict) or "cov" not in v:
            continue
        head, _, tail = key.partition("|K=")
        if tail and tail != "1":
            continue
        try:
            yield float(head.split("=")[1]), v
        except (IndexError, ValueError):
            continue


def main() -> None:
    sweep = json.loads(SWEEP.read_text())
    cells = sweep["cells"]

    # ONE population only. The low-t window (t = 0.20/0.25/0.30) lives in
    # setpred_dev_test.json, which is the 362-polygon *test* split, whereas this
    # sweep is the 1224-polygon pooled dev+test set. Mixing them would put rows
    # from different populations in the same column and make the trend
    # unreadable -- the policy-seed baseline alone differs between them
    # (|S|/OPT 1.21 pooled vs 1.09 on test). We therefore report only the
    # unreported high-t end here and cross-reference the headline tables for the
    # low-t window.
    rows = [(t, v["cov"], v.get("chv"), v.get("opt"))
            for t, v in _single_pass_cells(cells)]

    # dedupe by threshold, ascending
    seen, uniq = set(), []
    for r in sorted(rows):
        if r[0] in seen:
            continue
        seen.add(r[0])
        uniq.append(r)

    seed = sweep.get("seed") or {}

    lines = [
        "% auto-generated by build_operating_curve_table.py from",
        "% paper/data/setpred_iter_sweep.json (+ setpred_dev_test.json for the low-t end).",
        "% Combined dev+test pool, displayed seed 1234, single pass (K=1).",
        "% NOT cell-for-cell comparable with tab_headline (test-only, four-seed mean).",
        r"\begin{tabular}{lrrr}",
        r"  \toprule",
        r"  $t$ & Mean $\Covf{S}$ & Mean $|S|/n$ & Mean $|S|/\OPT$ \\",
        r"  \midrule",
    ]

    if seed:
        lines.append(
            rf"  \emph{{policy seed}} & {_fmt(seed.get('cov'), 4)} & "
            rf"{_fmt(seed.get('chv'))} & {_fmt(seed.get('opt'), 2)} \\"
        )
        lines.append(r"  \midrule")

    for t, cov, chv, opt in uniq:
        marker = r"$^{\ast}$" if abs(t - 0.20) < 1e-9 else ""
        lines.append(
            rf"  ${t:.2f}${marker} & {_fmt(cov, 4)} & {_fmt(chv)} & {_fmt(opt, 2)} \\"
        )

    lines += [r"  \bottomrule", r"\end{tabular}", ""]

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)}  ({len(uniq)} thresholds)")
    for t, cov, chv, opt in uniq:
        print(f"  t={t:.2f}  cov={cov:.4f}  |S|/n={chv:.4f}  |S|/OPT={opt:.3f}")


if __name__ == "__main__":
    main()
