#!/usr/bin/env python
"""build_operating_curve_table.py -- the probe's full coverage/cost operating curve.

The main tables report only t in {0.20, 0.25, 0.30}, the three most guard-expensive
points. This table traces the whole knob, t in [0.05, 0.80], with the policy seed
as a reference row.

SOURCE. Earlier revisions built this table from paper/data/setpred_iter_sweep.json,
which covers only the high-t end (t >= 0.5, single probe seed) because it was
computed for the fixed-point experiment. That file is on the correct 362-polygon
`test` split -- its K=1 cells agree to machine precision with the sweep used here
at the shared thresholds 0.5/0.6/0.8 -- but it cannot supply the low-t window or a
seed spread. The wide ablation sweep covers the whole range t in [0.05, 0.80] over
four probe seeds on the same split, so we use it instead and the table becomes
directly comparable to tab_headline and tab_ablation_thresholds.

The policy-seed row is byte-identical across the four probe seeds (it is the same
released policy 1234), so it carries no spread.

Source: paper/data/matched_budget/full_{1234,11,22,33}.json
Usage:  python paper/scripts/build_operating_curve_table.py
"""
from __future__ import annotations

import json
import pathlib

import numpy as np

REPO = pathlib.Path(__file__).resolve().parents[2]
SWEEP = REPO / "paper/data/matched_budget"
OUT = REPO / "paper/tables/tab_operating_curve.tex"

SEEDS = ("1234", "11", "22", "33")


def load():
    """(policy row, {t: [per-seed cells]}) from the four full-probe sweeps."""
    per_t: dict[float, list] = {}
    policy = None
    for s in SEEDS:
        d = json.loads((SWEEP / f"full_{s}.json").read_text())
        if policy is None:
            policy = d["seed"]
        for key, c in d["cells"].items():
            if not key.endswith("|K=1"):
                continue
            per_t.setdefault(float(key.split("|")[0].split("=")[1]), []).append(c)
    return policy, per_t


def agg(cells, path, nd):
    """mean +- std across probe seeds of one metric, formatted."""
    vals = [path(c) for c in cells]
    m, sd = float(np.mean(vals)), float(np.std(vals))
    if sd < 0.5 * 10 ** (-nd):          # spread invisible at this precision
        return f"${m:.{nd}f}$"
    return rf"${m:.{nd}f} \pm {sd:.{nd}f}$"


def main() -> None:
    policy, per_t = load()

    lines = [
        "% auto-generated by build_operating_curve_table.py from",
        "% paper/data/matched_budget/full_{1234,11,22,33}.json",
        "% 362-polygon held-out test split, leak-free probe, four-seed mean +- std,",
        "% single pass (K=1), coverage by exact CGAL. Same population as tab_headline.",
        r"\begin{tabular}{lrrrr}",
        r"  \toprule",
        r"  $t$ & Mean $\Covf{S}$ & Mean $|S|/n$ & Mean $|S|/\OPT$"
        r" & $\#\{\Covf{S} \ge 0.95\}$ \\",
        r"  \midrule",
        rf"  \emph{{policy seed}} & ${policy['cov']:.4f}$ & ${policy['chv']:.3f}$ &"
        rf" ${policy['opt']:.2f}$ & ${policy['dist']['n_cov_ge_095']}$ \\",
        r"  \midrule",
    ]

    for t in sorted(per_t):
        cells = per_t[t]
        marker = r"$^{\ast}$" if abs(t - 0.20) < 1e-9 else ""
        lines.append(
            rf"  ${t:.2f}${marker} & {agg(cells, lambda c: c['cov'], 4)} &"
            rf" {agg(cells, lambda c: c['chv'], 3)} &"
            rf" {agg(cells, lambda c: c['opt'], 2)} &"
            rf" {agg(cells, lambda c: c['dist']['n_cov_ge_095'], 1)} \\"
        )

    lines += [r"  \bottomrule", r"\end{tabular}", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)}  ({len(per_t)} thresholds)\n")
    print("\n".join(lines))

    print("\n--- crossover check (claims made in the text) ---")
    p = policy
    print(f"  policy seed: cov {p['cov']:.4f}  |S|/OPT {p['opt']:.3f}"
          f"  #>=0.95 {p['dist']['n_cov_ge_095']}/362")
    for t in sorted(per_t):
        c = per_t[t]
        cov = np.mean([x["cov"] for x in c])
        opt = np.mean([x["opt"] for x in c])
        g95 = np.mean([x["dist"]["n_cov_ge_095"] for x in c])
        flags = []
        if cov < p["cov"]:
            flags.append("cov BELOW policy")
        if opt < p["opt"]:
            flags.append("cheaper than policy")
        if g95 < p["dist"]["n_cov_ge_095"]:
            flags.append("gate BELOW policy")
        print(f"  t={t:.2f}  cov={cov:.4f}  |S|/OPT={opt:.3f}  #>=0.95={g95:.1f}"
              + ("   <- " + ", ".join(flags) if flags else ""))


if __name__ == "__main__":
    main()
