"""Build LaTeX tables in paper/tables/ from JSON results in paper/data/.

Run: python paper/scripts/build_tables.py
Output: paper/tables/tab_*.tex
Each table is a `tabular` environment ready to \\input{} from paper.tex.
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
TABLES = ROOT / "tables"
TABLES.mkdir(exist_ok=True)


def load(name: str) -> dict:
    return json.loads((DATA / name).read_text())


def wilson_ci(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    """Wilson 95% CI for binomial proportion."""
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    denom = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / denom
    half = (z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))) / denom
    return (max(0.0, centre - half), min(1.0, centre + half))


def write(name: str, body: str) -> None:
    out = TABLES / name
    out.write_text(body)
    print(f"wrote {out.relative_to(ROOT.parent)}")


# ---------- tab_headline: dev_test seed vs t=0.20 ----------
def tab_headline() -> None:
    d = load("setpred_dev_test.json")
    seed = d["seed"]
    cell = d["cells"]["t=0.2|K=1"]
    n = d["n_polygons"]
    lo_seed, hi_seed = wilson_ci(seed["dist"]["n_cov_ge_095"], n)
    lo_t, hi_t = wilson_ci(cell["dist"]["n_cov_ge_095"], n)
    body = (
        "% auto-generated by build_tables.py from data/setpred_dev_test.json\n"
        "\\begin{tabular}{lrrr}\n"
        "  \\toprule\n"
        "  Method & Mean coverage & $\\#\\{\\mathrm{Cov}\\ge 0.95\\}/n$ & Mean $|S|/\\OPT$ \\\\\n"
        "  \\midrule\n"
        f"  Pretrained pointer (seed) & {seed['cov']:.4f} & "
        f"{seed['dist']['n_cov_ge_095']}/{n}\\,({lo_seed:.3f},{hi_seed:.3f}) & "
        f"{seed['opt']:.4f} \\\\\n"
        f"  SetPredictor ($t=0.20$)   & \\textbf{{{cell['cov']:.4f}}} & "
        f"\\textbf{{{cell['dist']['n_cov_ge_095']}/{n}}}\\,({lo_t:.3f},{hi_t:.3f}) & "
        f"{cell['opt']:.4f} \\\\\n"
        "  \\bottomrule\n"
        "\\end{tabular}\n"
    )
    write("tab_headline.tex", body)


# ---------- tab_dist_shift: per-polygon coverage distribution ----------
def tab_dist_shift() -> None:
    d = load("setpred_dev_test.json")
    n = d["n_polygons"]
    rows = [("Pretrained pointer (seed)", d["seed"]["dist"]),
            ("SetPredictor $t=0.20$", d["cells"]["t=0.2|K=1"]["dist"]),
            ("SetPredictor $t=0.25$", d["cells"]["t=0.25|K=1"]["dist"]),
            ("SetPredictor $t=0.30$", d["cells"]["t=0.3|K=1"]["dist"])]
    lines = [
        "% auto-generated by build_tables.py from data/setpred_dev_test.json",
        "\\begin{tabular}{lrrrrr}",
        "  \\toprule",
        "  Method & $\\#\\{\\mathrm{Cov}=1\\}$ & $\\#\\{\\mathrm{Cov}\\ge .999\\}$ & "
        "$\\#\\{\\mathrm{Cov}\\ge .99\\}$ & $\\#\\{\\mathrm{Cov}\\ge .95\\}$ & min $\\mathrm{Cov}$ \\\\",
        "  \\midrule",
    ]
    for name, dist in rows:
        lines.append(
            f"  {name} & {dist['n_cov_eq_1']} & {dist['n_cov_ge_0999']} & "
            f"{dist['n_cov_ge_099']} & {dist['n_cov_ge_095']}/{n} & "
            f"{dist['cov_min']:.3f} \\\\"
        )
    lines += ["  \\bottomrule", "\\end{tabular}", ""]
    write("tab_dist_shift.tex", "\n".join(lines))


# ---------- tab_pareto: threshold sweep on dev_test ----------
def tab_pareto() -> None:
    d = load("setpred_dev_test.json")
    n = d["n_polygons"]
    cells = d["cells"]
    lines = [
        "% auto-generated by build_tables.py from data/setpred_dev_test.json",
        "\\begin{tabular}{lrrrr}",
        "  \\toprule",
        "  Threshold $t$ & Mean $\\mathrm{Cov}$ & Mean $|S|/n$ & Mean $|S|/\\OPT$ & "
        "$\\#\\{\\mathrm{Cov}\\ge .95\\}/n$ \\\\",
        "  \\midrule",
    ]
    order = ["t=0.2|K=1", "t=0.25|K=1", "t=0.3|K=1"]
    label = {"t=0.2|K=1": "0.20", "t=0.25|K=1": "0.25", "t=0.3|K=1": "0.30"}
    for k in order:
        c = cells[k]
        lines.append(
            f"  {label[k]} & {c['cov']:.4f} & {c['chv']:.4f} & "
            f"{c['opt']:.4f} & {c['dist']['n_cov_ge_095']}/{n} \\\\"
        )
    lines += ["  \\bottomrule", "\\end{tabular}", ""]
    write("tab_pareto.tex", "\n".join(lines))


# ---------- tab_fixed_point: K=1,2,3,5 from iter sweep ----------
def tab_fixed_point() -> None:
    d = load("setpred_iter_sweep.json")
    cells = d["cells"]
    t_show = "0.65"
    lines = [
        "% auto-generated by build_tables.py from data/setpred_iter_sweep.json",
        "\\begin{tabular}{lrrr}",
        "  \\toprule",
        "  Inference passes $K$ & Mean $\\mathrm{Cov}$ & Mean $|S|/n$ & Mean $|S|/\\OPT$ \\\\",
        "  \\midrule",
    ]
    for K in [1, 2, 3, 5]:
        key = f"t={t_show}|K={K}"
        if key in cells:
            c = cells[key]
            lines.append(
                f"  $K={K}$ & {c['cov']:.4f} & {c['chv']:.4f} & {c['opt']:.4f} \\\\"
            )
    lines += ["  \\bottomrule", "\\end{tabular}", ""]
    write("tab_fixed_point.tex", "\n".join(lines))


# ---------- tab_ood_test: OOD on test/ split ----------
def tab_ood_test() -> None:
    d = load("setpred_test_OOD.json")
    n = d["n_polygons"]
    seed = d["seed"]
    cell_t02 = d["cells"]["t=0.2|K=1"]
    cell_t025 = d["cells"]["t=0.25|K=1"]
    cell_t03 = d["cells"]["t=0.3|K=1"]
    lines = [
        "% auto-generated by build_tables.py from data/setpred_test_OOD.json",
        "\\begin{tabular}{lrrrr}",
        "  \\toprule",
        "  Method & Mean $\\mathrm{Cov}$ & $\\#\\{\\mathrm{Cov}\\ge .95\\}/n$ & "
        "min $\\mathrm{Cov}$ & Mean $|S|/\\OPT$ \\\\",
        "  \\midrule",
    ]
    rows = [
        ("Pretrained pointer (seed)", seed["cov"], seed["dist"], seed["opt"]),
        ("SetPredictor $t=0.20$", cell_t02["cov"], cell_t02["dist"], cell_t02["opt"]),
        ("SetPredictor $t=0.25$", cell_t025["cov"], cell_t025["dist"], cell_t025["opt"]),
        ("SetPredictor $t=0.30$", cell_t03["cov"], cell_t03["dist"], cell_t03["opt"]),
    ]
    for name, cov, dist, opt in rows:
        opt_s = f"{opt:.4f}" if opt is not None else "--"
        lines.append(
            f"  {name} & {cov:.4f} & {dist['n_cov_ge_095']}/{n} & "
            f"{dist['cov_min']:.3f} & {opt_s} \\\\"
        )
    lines += ["  \\bottomrule", "\\end{tabular}", ""]
    write("tab_ood_test.tex", "\n".join(lines))


# ---------- tab_dataset_partition: hand-curated partition statistics ----------
def tab_dataset_partition() -> None:
    # Numbers come from paper.md §5 (dataset size distribution).
    body = (
        "% hand-curated dataset partition table\n"
        "\\begin{tabular}{lrrr}\n"
        "  \\toprule\n"
        "  Split & \\# polygons & $n$ range & Use \\\\\n"
        "  \\midrule\n"
        "  train      & 9{,}791 & 8--150  & Pointer + SetPredictor training \\\\\n"
        "  dev\\_tune & 857     & 8--150  & SetPredictor checkpoint selection \\\\\n"
        "  dev\\_test & 367     & 8--150  & Held-out evaluation (in-distribution) \\\\\n"
        "  test       & 2{,}107 & 12--1{,}000 & Out-of-distribution evaluation \\\\\n"
        "  large      & 20      & 1{,}000--2{,}250 & Extreme OOD (smoke) \\\\\n"
        "  \\bottomrule\n"
        "\\end{tabular}\n"
    )
    write("tab_dataset_partition.tex", body)


if __name__ == "__main__":
    tab_headline()
    tab_dist_shift()
    tab_pareto()
    tab_fixed_point()
    tab_ood_test()
    tab_dataset_partition()
