"""Probe-capacity ladder table (reviewer R3): does an intermediate-capacity probe
already recover the guard-relevant signal, or is the full 464K Transformer's
nonlinear reasoning doing the work?

Combines two sources, both on the leak-free dev_test split:
  - probe_ladder.json  : per-vertex ROC-AUC per capacity (eval_probe_ladder.py)
  - dist_dev_test_*.json: downstream #Cov<0.99 and |S|/OPT at t=0.20 (4-seed mean)

Rows: linear -> attention-free MLP -> 1 self-attention layer -> full SetPredictor.
The linear rung is AUC-only (a logistic readout, not thresholded into a guard set),
so its downstream cells are left blank.

Output: paper/tables/tab_probe_ladder.tex

Usage:
  python paper/scripts/build_ladder_table.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
PDATA = REPO / "paper" / "data"
TABLE = REPO / "paper" / "tables" / "tab_probe_ladder.tex"

# capacity -> dist_dev_test files (4 seeds) for downstream metrics at t=0.20
DOWNSTREAM = {
    "mlp":   [f"dist_dev_test_ladder_mlp_seed{s}.json"   for s in (1234, 11, 22, 33)],
    "attn1": [f"dist_dev_test_ladder_attn1_seed{s}.json" for s in (1234, 11, 22, 33)],
    "full":  ["dist_dev_test.json", "dist_dev_test_seed11.json",
              "dist_dev_test_seed22.json", "dist_dev_test_seed33.json"],
}
LABEL = {
    "linear": "Linear (logistic)",
    "mlp":    "Attention-free MLP",
    "attn1":  "1 self-attention layer",
    "full":   "Full \\SetPredictor{} (3 layers)",
}
ORDER = ["linear", "mlp", "attn1", "full"]


def downstream(files, key="probe_t020"):
    below, sopt = [], []
    for f in files:
        fp = PDATA / f
        if not fp.exists():
            return None, None
        d = json.load(open(fp))["polygons"]
        below.append(sum(1 for r in d if r[key]["cov"] < 0.99))
        sopt.append(np.mean([r[key]["S_size"] / r["OPT"] for r in d if r.get("OPT")]))
    return (float(np.mean(below)), float(np.std(below))), (float(np.mean(sopt)), float(np.std(sopt)))


def main() -> None:
    ladder = json.load(open(PDATA / "probe_ladder.json"))
    auc = {r["name"]: r for r in ladder["rows"]}

    rows = ["% auto-generated by build_ladder_table.py",
            "\\begin{tabular*}{0.96\\textwidth}{@{\\extracolsep{\\fill}}lrrr}", "  \\toprule",
            "  Probe capacity & Params & ROC-AUC & PR-AUC \\\\",
            "  \\midrule"]
    for name in ORDER:
        r = auc.get(name, {})
        p = r.get("n_params")
        pstr = f"{p:,}" if p else "---"
        am, asd = r.get("roc_auc_mean"), r.get("roc_auc_std") or 0.0
        pm, psd = r.get("pr_auc_mean"), r.get("pr_auc_std") or 0.0
        aucstr = f"{am:.3f}\\,$\\pm$\\,{asd:.3f}" if am is not None else "---"
        prstr = f"{pm:.3f}\\,$\\pm$\\,{psd:.3f}" if pm is not None else "---"
        rows.append(f"  {LABEL[name]} & {pstr} & {aucstr} & {prstr} \\\\")
    rows += ["  \\bottomrule", "\\end{tabular*}"]
    TABLE.write_text("\n".join(rows) + "\n")
    print(f"wrote {TABLE}")
    print("\n".join(rows))


if __name__ == "__main__":
    main()
