#!/usr/bin/env python
"""build_ablation_table.py — the 2x2 encoder/seed ablation requested by the
Stanford reviewer (Q2). Reads the per-polygon dist_*.json files for all four
conditions on the in-distribution test split, aggregates 4-seed mean +/- std,
and writes paper/tables/tab_ablation.tex plus paper/data/ablation_2x2.json
(the latter for prose numbers).

Conditions (each = 4 seeds {1234,11,22,33}):
  full        encoder + seed   dist_dev_test{,_seed*}.json
  noseed      encoder only     dist_dev_test_noseed_seed*.json
  noencoder   seed only        dist_dev_test_noenc{,_seed*}.json
  coordsonly  neither          dist_dev_test_noseednoenc_seed*.json

The encoder's contribution shows in the tail (# below 0.99 and min Cov), so those
are the headline columns; |S|/OPT reports the matched cost. All at t=0.20.
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PAPER_DATA = os.path.join(REPO_ROOT, "paper", "data")
PAPER_TABLES = os.path.join(REPO_ROOT, "paper", "tables")

# condition -> (label, encoder?, seed?, [seed-file basenames in dev_test])
CONDITIONS = [
    ("full",       "\\SetPredictor{} full",        True,  True,
     ["dist_dev_test.json", "dist_dev_test_seed11.json",
      "dist_dev_test_seed22.json", "dist_dev_test_seed33.json"]),
    ("noseed",     "\\quad no-seed (encoder $+$ coords)", True,  False,
     ["dist_dev_test_noseed_seed1234.json", "dist_dev_test_noseed_seed11.json",
      "dist_dev_test_noseed_seed22.json", "dist_dev_test_noseed_seed33.json"]),
    ("noencoder",  "\\quad no-encoder (seed $+$ coords)", False, True,
     ["dist_dev_test_noenc.json", "dist_dev_test_noenc_seed11.json",
      "dist_dev_test_noenc_seed22.json", "dist_dev_test_noenc_seed33.json"]),
    ("coordsonly", "\\quad coords-only",  False, False,
     ["dist_dev_test_noseednoenc_seed1234.json", "dist_dev_test_noseednoenc_seed11.json",
      "dist_dev_test_noseednoenc_seed22.json", "dist_dev_test_noseednoenc_seed33.json"]),
]

KEY = "probe_t020"


def _per_seed_metrics(path: str) -> dict:
    rows = json.load(open(path))["polygons"]
    cov = np.array([r[KEY]["cov"] for r in rows])
    sopt = [r[KEY]["S_size"] / r["OPT"] for r in rows if r.get("OPT")]
    son = [r[KEY]["S_size"] / r["n"] for r in rows]
    return {
        "n": len(rows),
        "below_099": int((cov < 0.99).sum()),
        "below_095": int((cov < 0.95).sum()),
        "mean_cov": float(cov.mean()),
        "min_cov": float(cov.min()),
        "s_over_opt": float(np.mean(sopt)) if sopt else float("nan"),
        "s_over_n": float(np.mean(son)),
    }


def _agg(files: list[str]) -> dict | None:
    paths = [os.path.join(PAPER_DATA, f) for f in files]
    missing = [p for p in paths if not os.path.exists(p)]
    if missing:
        print(f"  [skip] missing {len(missing)} file(s): "
              f"{', '.join(os.path.basename(m) for m in missing)}")
        return None
    per = [_per_seed_metrics(p) for p in paths]
    n = per[0]["n"]
    out = {"n": n, "n_seeds": len(per), "per_seed_below_099": [p["below_099"] for p in per]}
    for k in ("below_099", "below_095", "mean_cov", "min_cov", "s_over_opt", "s_over_n"):
        vals = np.array([p[k] for p in per], dtype=float)
        out[f"{k}_mean"] = float(np.nanmean(vals))
        out[f"{k}_std"] = float(np.nanstd(vals))
    return out


def main() -> None:
    results = {}
    n_total = None
    print("[ablation] aggregating 2x2 conditions on dev_test (t=0.20)")
    for cid, label, enc, seed, files in CONDITIONS:
        agg = _agg(files)
        if agg is None:
            print(f"  {cid}: INCOMPLETE")
            continue
        agg["label"] = label
        agg["encoder"] = enc
        agg["seed"] = seed
        results[cid] = agg
        n_total = agg["n"]
        print(f"  {cid:<11} below0.99={agg['below_099_mean']:.2f}±{agg['below_099_std']:.2f} "
              f"minCov={agg['min_cov_mean']:.3f} |S|/OPT={agg['s_over_opt_mean']:.3f}")

    # JSON for prose
    out_json = os.path.join(PAPER_DATA, "ablation_2x2.json")
    json.dump({"split": "dev_test", "threshold": 0.20, "conditions": results},
              open(out_json, "w"), indent=2)
    print(f"[ablation] wrote {out_json}")

    # only emit the LaTeX table if all four cells are present
    if len(results) < 4:
        print("[ablation] fewer than 4 conditions complete — JSON written, "
              "skipping tab_ablation.tex until all dist files exist.")
        return

    def cm(flag):
        return "$\\checkmark$" if flag else "$\\times$"

    lines = [
        "% auto-generated by build_ablation_table.py from paper/data/dist_dev_test_*.json",
        "\\begin{tabular}{lrrrr}",
        "  \\toprule",
        "  Probe inputs & $\\#\\{\\mathrm{Cov}<0.99\\}$ & "
        "$\\min \\mathrm{Cov}$ & $|S|/n$ & $|S|/\\OPT$ \\\\",
        "  \\midrule",
    ]
    for cid, _, _, _, _ in CONDITIONS:
        r = results[cid]
        lines.append(
            f"  {r['label']} & "
            f"${r['below_099_mean']:.1f} \\pm {r['below_099_std']:.1f}$ & "
            f"{r['min_cov_mean']:.3f}\\,$\\pm$\\,{r['min_cov_std']:.3f} & "
            f"{r['s_over_n_mean']:.2f}\\,$\\pm$\\,{r['s_over_n_std']:.2f} & "
            f"{r['s_over_opt_mean']:.2f}\\,$\\pm$\\,{r['s_over_opt_std']:.2f} \\\\"
        )
    lines += ["  \\bottomrule", "\\end{tabular}", ""]
    out_tex = os.path.join(PAPER_TABLES, "tab_ablation.tex")
    with open(out_tex, "w") as fh:
        fh.write("\n".join(lines))
    print(f"[ablation] wrote {out_tex} (N={n_total} polygons)")


if __name__ == "__main__":
    main()
